spring:
  application:
    name: hw-kafka-example
  kafka:
    bootstrap-servers: 192.168.10.7:9092, 192.168.10.8:9092, 192.168.10.9:9092
    producer:
      key-serializer: String
      value-serializer: String
    consumer:
      group-id: hw_kafka_group
      auto-offset-reset: earliest
      key-deserializer: String
      value-deserializer: String